### ISSUE TITLE
Selected criteria should always be shown - even when clicking 'Show Less'

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#101]
A selected criteria should remain visible even when choosing to show less.

**Comment by assafharel** [comment]
Another case for that is that when selecting a criteria (or product) that wasn't visible, it should be made visible. For instance, when selecting a whole topic (for instance, 8 criteria) and only 3 are visible before selection, the entire 8 should be made visible.

**Comment by assafharel** [comment]
The new UI for this is explained in issue #80.
