### ISSUE TITLE
RFE - add mixpanel to the application pages

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#102]
I want to be able to monitor use of the application (as well as the landing page).

**Comment by assafharel** [comment]
Brought it back from Someday to Sprint#1 as we want to monitor what users are doing with the App.
Please add an event per page, so we will be able to monitor a user behavior in the system (page wize).

Thanks,
Assaf


Thanks,
Assaf

**Comment by Pavek** [comment]
Please define the following:
- exact names of all events
- exact time when triggered
Note: if the answers are 'equals to page url' and 'upon navigation', then
probably Google Analytics is a better place for it (does it automatically)

**Comment by assafharel** [comment]
I don’t mind switching to Google Analytics.
It’s must easier for me to find myself in Mixpanel, but I will gladly learn GA if it’s easier for you to implement.
The events would indeed be “Products page loaded”, “Criteria page loaded”, etc.
Also, very important is signup, and login.

Regards,
Assaf


Assaf Harel, CTO and Co-Founder,
+972.52.7206732
