### ISSUE TITLE
Functionality Criteria should be Category based

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#113]
(and change when switching between categories)

**Comment by Pavek** [comment]
I don't understand this. Originally, Products were based on Catagory. Criteria has no links with category, only with topics. Is this about to chnage? Please elaborate how.

**Comment by assafharel** [comment]
Most criteria are indeed non category related.
But there are criteria that are category related, we call them functionality criteria.
You have different functionality criteria for a security product then you have for storage, maketing or HR.
I understand that it's a change to design, but we have to do it.
When a user selects a category she has to see only criteria that are relevant, which means all the general ones, and the category specific.
