### ISSUE TITLE
Popularity should be presented with bars and not with percentage

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#114]

**Comment by Pavek** [comment]
Any example of it is welcome. Also were exactly it should be displayed?

**Comment by assafharel** [comment]
Displayed: on the list exactly where the numbers are presented today.
Example: Assigning to Tal who had the original one. I didn't find a good example in Amazon.com, Cnet.com and Tripadvisor.com

**Comment by Pavek** [comment]
Nice place to search design ideas is Dribble. Here's items tagged 'popularity':
https://dribbble.com/tags/popularity

Here's the item I found there:
https://dribbble.com/shots/981967-Popularity-panel?list=tags&tag=popularity&offset=6

Let me know if it is what required (alos note that is has strong connection with 'signal strength' or 'battery life').

**Comment by assafharel** [comment]
I liked this one better:
https://dribbble.com/shots/764434-Freebie-Popularity-meter?list=tags&tag=popularity&offset=8
But I leave it to Tal to decide, as he's the original owner of this issue, and I think that he has a clear vision of what he wants to see there.

**Comment by assafharel** [comment]
Hi Pavel,

After discussing with Tal, please use this one.
https://dribbble.com/shots/764434-Freebie-Popularity-meter?list=tags&tag=popularity&offset=8

Thanks,
Assaf
