### ISSUE TITLE
Seperate left navigation scrolling from main window scrolling (vertical)

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#129]

**Comment by Pavek** [comment]
Not sure what it means. Do you mean 'freazing' side menu to make it always visible?
Then there are at least 2 ways to do that:
- like Gmail - always static, only main content is scrollable, but note that it makes the whole header  freeze & probably requires iframes (a lot of changes)
- bootrtap affix way ([demo](http://getbootstrap.com/css/)): i.e. freeze after certain number of px is scrolled from top

**Comment by assafharel** [comment]
I prefer the gmail way. 
Notice that on gmail the left side is also scrollable. 
Still, this is not a very urgent / important matter, so don't go into it if it's too complicated. 

Assaf

**Comment by Pavek** [comment]
The impl has drawbacks: e.g. scrolling may 'flicker' screen in some (rare, I believe) combinations of screen/contnet/sidebar size. It is better to fix them when layout is finalized by designer.

**Comment by assafharel** [comment]
OK. Cool. Implemnation looks very nice.
