### ISSUE TITLE
Decision table - start with all topics closed and change the grade calculation

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#142]
1. Every topic should show it's own grade and not its part of the total grade.
2. Decision table should "remember" the state of the topics (collapsed vs. expanded) and stay the same on the next browse to it.

**Comment by Pavek** [comment]
So, I guess what's left here is a persistence of collapsed state for every topic+project. Please confirm.

**Comment by assafharel** [comment]
Confirned.
