### ISSUE TITLE
Decision table is not showing full 3 candidates on my screen

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#146]
I am working at resolution 1366x768.
I want 3 products to fit well on my screen when I expand the display.
Currently the 3rd product is only partially shown.

**Comment by Pavek** [comment]
Please send the following info:
- open Chrone DevTools (F12)
- switch to Console tab and run 'window.screen'
- post output here.

It should look something like:
availHeight: 1040
availLeft: 0
availTop: 0
availWidth: 1920
colorDepth: 24
height: 1080
pixelDepth: 24
width: 1920

**Comment by talbendavid** [comment]
Done:


   1. availHeight: 728
   2. availLeft: 0
   3. availTop: 0
   4. availWidth: 1366
   5. colorDepth: 24
   6. height: 768
   7. pixelDepth: 24
   8. width: 1366





*Tal Ben-David*, *CEO & Co-**Founder*
+972.52.4739064

**Comment by assafharel** [comment]
I suffer from the same issue, and on my machine it’s:
availHeight: 693
availLeft: 0
availTop: 23
availWidth: 1366
colorDepth: 24
height: 768
orientation: ScreenOrientation
pixelDepth: 24
width: 1366
__proto__: Screen

window.screen
Screen { availWidth: 1366, availHeight: 693, width: 1366, height: 768, colorDepth: 24, pixelDepth: 24, top: 0, left: 0, availTop: 23, availLeft: 0 }



Assaf Harel, CTO and Co-Founder,
+972.52.7206732
