### ISSUE TITLE
Chrome offers to save password even when login failed

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#15]
I tried to login with email and password that didn't exist.
The authentication failed as expected, but chrome popped up a dialog box offering to save the password.
This popup should only appear if authentication succeeded.

**Comment by Pavek** [comment]
Fixed with ca81683934 & 12f9d2b44 as descibed here: http://stackoverflow.com/questions/2382329/how-can-i-get-browser-to-prompt-to-save-password
