### ISSUE TITLE
Grades should be centered

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#166]
Currently, (probably because of the spinners) the grades are slightly to the left of the cell. They should centered as if there are no spinners.

**Comment by Pavek** [comment]
I guess this is non-Webkit browser. There is special fix implemented already for Webkit browsers using vendor-prefixed css (&::-webkit-inner-spin-button). Other browsers do not support this, unfortunately.

**Comment by assafharel** [comment]
Firefox on Mac?
How can you get more standard then that...


Assaf Harel, CTO and Co-Founder,
+972.52.7206732

**Comment by Pavek** [comment]
In Firefox you cannot control this.

**Comment by assafharel** [comment]
OK
