### ISSUE TITLE
Presentation - pdf - tables do not fit pages nicely

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#169]
Although the tables fit the presentation perfectly, they are all messy in the pdf. break in the middle and continue in another page, etc.

**Comment by Pavek** [comment]
- Please attach snapshot of the issue to let me reproduce it.
- Also note that PhantomJS browser used to generate PDF *may* produce different results on different platforms, hypothetically, so it is preferable to test on Heroku.
- Finally, updating to PhantomJS versoin 2.0 may help. At least it supports WebFonts which is now obviously missed (fonts in HTML and PDF do not match). But is still not very stable version (see [this bug](https://github.com/Medium/phantomjs/issues/288)). Incidently, one of the issues is that [PDF rendering is broken](https://github.com/ariya/phantomjs/issues/12685).

**Comment by assafharel** [comment]
With the new version, it's not reproduced any more. Closing.

**Comment by assafharel** [comment]
Reopen as I have a reproduction:
https://www.peer-say.com/files/oChdnbV2/Payment%20Solution%20-%20Sep%209th%202015%20-%20%231.pdf

**Comment by Pavek** [comment]
I believe I fixed this severe example with the commit above. I still see less severe PDF rendering issues like title truncation here: https://gyazo.com/6a0b3af678002b6fd0689562e3b1bcb8

I think this is related to general font rendering issues that current version of PhantomJS has, that are descibed above.

So, I propose to verify and postpone to later times with a note: upgrade to PhantomJS 2.0 and re-test.

**Comment by assafharel** [comment]
OK.
בתאריך Fri, Sep 11, 2015 ב-18:09 מאת Pavel Zhytko <notifications@github.com
