### ISSUE TITLE
The topic percentage control sometimes doesn't add up to 100%

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#173]
Sometimes the control ends up below 100%.
For example, I had 3 topics, and I set the first to 20% the second to 40% and the third ended up with 39% (instead of 40%).

The sum should always be 100%.

**Comment by Pavek** [comment]
I guess what you see is a normal effect of rounding up. Consider this example:

Values: | Round to .1 | Round to int
----------|----------------|------------------
0.2040 | 20.4%| 20%
0.4040 | 40.4%| 40%
0.3920 | 39.2%| 39%
Total: 1 | | 

So, calculation is correct here, but rounding produces the result you see. Any suggestions how to improve this are welcome.

**Comment by assafharel** [comment]
It shouldn’t be so precise.
i.e. the steps shouldn’t be of Decimal points, but rather of whole integers, so no rounding will be required.

Regards,
Assaf


Assaf Harel, CTO and Co-Founder,
+972.52.7206732

**Comment by Pavek** [comment]
Becasue of the requirement to "divide equally between all", the effective operation to produce the result is division, which necessarily produces floating-point numbers, no matter what is the whole (in our cases this is 1). So, we store them as floats and rounding is a presentational detail/concern.

The opposite solution would be 'divide into integer numbers almost-equally', which I don't know how to implement effectively.

**Comment by assafharel** [comment]
I see.
So let’s separate the problem to 2 phases:
1. When dividing and the result is less then 100% add whatever is missing to the last topic (usually it’s Cost, so it even makes sense).
2. In the weight distribution control work with Integers.

Regards,
Assaf


Assaf Harel, CTO and Co-Founder,
+972.52.7206732
