### ISSUE TITLE
Presentation: Cost slide should include details and not only grades

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#176]
The cost slide should show the detailed cost information and not only the grade.

**Comment by Pavek** [comment]
So you mean that Input columns should be displayed for all product columns?

**Comment by talbendavid** [comment]
Yes (for the 3 products we show)
בתאריך יום ב׳, 7 בספט׳ 2015 ב-16:57 מאת Pavel Zhytko <
notifications@github.com>:

**Comment by Pavek** [comment]
Is this possible to show it inline without adding a separate columns like this?
https://gyazo.com/08316242f3697175cb7a3166b6c522b0

It could save a lot of time & code.

**Comment by Pavek** [comment]
Another example: https://gyazo.com/6cabeaef9b7e61addba98b90efcef1bc

**Comment by talbendavid** [comment]
Go for it.
בתאריך יום ה׳, 10 בספט׳ 2015 ב-18:13 מאת Pavel Zhytko <
notifications@github.com>:
