### ISSUE TITLE
Improvements to Project Essentials tile

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#19]
Only the fields are clickable. When clicked the full tile is opened anyway, so the entire area of these fields should be clickable.

The date fields don't work when trying to edit (tested on Chrome)

The shortlist and team members are clickable but do nothing. These sections have hardcoded values in them that should be removed.
Suggest to put in grey color saying "No products added yet" and "Click to add team members" respectively.

The title field is too short.
Domain field should be shown.
Title and Domain should not have an 'OK' image (user sets them, so it is not a guess we validate)

**Comment by Pavek** [comment]
Invalid due to new Essentials dialog design.
