### ISSUE TITLE
Improvements to Criteria tile

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#20]
Group should be renamed to Topic

The closed tile should be presented with headers as the user selected in the open tile.
Once this is so, then the Group column is not needed in the closed tile.

Required/Optional should be capitalized (in the future switch to icons).

No way to remove or rename a Group (Topic) - even if I just make a typo - I am stuck with it forever.

Popup menus not working in Firefox and Safari on Mac.

**Comment by Pavek** [comment]
The only item left is:
- Required/Optional should be capitalized
