### ISSUE TITLE
Decision table issues

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#24]
1. Weights should be displayed between 0 and 100 (they are already calculated so in the grade)
2. Zero weights should not appear as zero. Lines with zero weight should be grayed out.
3. Overall grade should be in same units as other grades. Can have 1 decimal point.
4. The colors are unclear.

**Comment by Pavek** [comment]
1-3. Agreed.Product grade is still 0-10.
2. Agreed.
4. Post-alpha
