### ISSUE TITLE
Enable easily adding product names into the evaluation table

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#25]
Provide anasy way to add a product into the table,
For example from the product's web page.
Possibly requires a browser addon.

**Comment by Pavek** [comment]
Few comments:
- For example from the product's web page.
> 'Product's web page'? - it was not defined before I believe.

- Possibly requires a browser addon.
> I don't see any reason why. Please elaborate.

Idea:
- We have (+)Add item in Nav menu. It can have any items(actions.)

**Comment by Pavek** [comment]
Is this still required with new UX? Please elaborate.
