### ISSUE TITLE
Add a place to write a summary and recommendations

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#27]

**Comment by Pavek** [comment]
Mock-up is required.

**Comment by talbendavid** [comment]
I will send a mockup ppt by mail as GIT doesn't support adding a ppt.
The mockup suggests a very simple solution to this requirement.
The reason is that when I was considering what to put where, I understood that we are using the screen real-estate too loosely, and we're out of quality space.
I decided that a major refactor will wait for the UX work we started, and for now to go with a simple solution. If the solution requires a significant investment, then we should discuss and consider reducing it more.

**Comment by Pavek** [comment]
Mock-up: http://gyazo.com/cb6f50a81e92f35245d0717eab75ca99
