### ISSUE TITLE
Fix progress arrows

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#30]
make all buttons appear directional on both sides (even when first or last)
Remove green progress bar

**Comment by Pavek** [comment]
Need some mock-up - it's is unclear how to do this. To me, double-arrows means no arrows, as following:
http://gyazo.com/f632465f949506a3cc8d3018153e5d35

**Comment by Pavek** [comment]
Low priority. So far for non-mobile view only.
