### ISSUE TITLE
Project essentials are displayed without context

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#38]
When add budget info I only see the number(s) I added without context.
The header 'Expected Budget' should be shown.

The time should be formatted to say "Starting <date> for <duration>"

**Comment by Pavek** [comment]
Please provide a new mock-up - this was done according to Assaf's mock-up / spec.

**Comment by talbendavid** [comment]
Attaching a mockup (contains before and after screenshots)

![essentials presentation mockup](https://cloud.githubusercontent.com/assets/8959176/6557064/d9e55c62-c67a-11e4-97d6-c0c8f6466345.png)
