### ISSUE TITLE
When opening an existing project that has all forms filled not tables are shown.

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#42]
Open an existing project that has all tables (criteria, product, decision),
The progress bar is full, but the table are not shown.

How to recover?
Click refresh. The progress will show only 'Essentials' as done.
Click on essentials to open the form and then move from form to form (e.g. in essentials click 'Criteria').
The table forms will reappear and then appear on screen.

**Comment by Pavek** [comment]
The Wizard logic is not fully implemented - consider it a demo mode. I'm not sure how exactly the Wizard should work -- we need to discuss it.
