### ISSUE TITLE
Add the PeerSay logo to the LinkedIn login page

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#43]
The LinkedIn login dialog has a placeholder for the company logo (top right).
You can see used in other sites - for example on g2crowd.com.

**Comment by Pavek** [comment]
Seems it should be configured in LinkedIn application settings, as described here:
https://developer.linkedin.com/docs/oauth2 (see The User Experience section)

The link suggested is https://www.linkedin.com/secure/developer
It should be accessed/configured by Assaf, who created the LinkedIn app, I guess.

**Comment by assafharel** [comment]
Fixed on our LinkedIn app profile.
