### ISSUE TITLE
Shortlist doesn't expand well when adding criteria

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#44]
I added criteria after the shortlist existed and the new lines were not presented properly:
Gridlines were not added, and cells were empty.

![image](https://cloud.githubusercontent.com/assets/8959176/6557598/ebc1d8bc-c67e-11e4-8f65-5e207a18c0c6.png)

**Comment by Pavek** [comment]
This wasd fixed by recent commits I believe. Notably, the values (0) are now always displayed in cells.

Please re-open if reproduced.
