### ISSUE TITLE
Products may disappear after certain actions

### ISSUE THREAD

**Issue by Pavek** [PeerSay/Atlas#54]
Test case:
1. Create 1 Criteria
2. Create 2 Products
3. Create 2nd Criteria
4. remove 1st Criteria (top row)
5. Go back to Product Input
6. Press F5 (i.e. reload model from server)
-> Products disappear.

The reason is that Products exist as properties of Criteria object and they are lazily added to new Criteria when input/score is edited. That is, when no input/score is added to certain Criteria, then it has no information about Products, thus when this information is removed from all other Criterias, then it is gone forever. This is a model issue.

**Comment by assafharel** [comment]
alpha critical
