### ISSUE TITLE
new landing page | 2 white sections one after the other

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#60]
Hi Pavel,

Every section should have its unique color and so did Anish (the designer) planned it. But since we removed Team and Map, there are now 2 white sections one after the others.

Please solve this by taking the grey background from the team section in the original PSD, and use it as background for Contact ("Get to know us better").

Assaf

**Comment by Pavek** [comment]
In fact, on PSD last two sections are both white - Team & Contact.
