### ISSUE TITLE
new landing page | add "privacy" and "terms and conditions" pages

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#62]

**Comment by assafharel** [comment]
https://www.dropbox.com/s/uzgvjh9ogv301df/PeerSay%20-%20Privacy%20Policy%20-%20clean.docx?dl=0

https://www.dropbox.com/s/93ywi7gop39gcgg/PeerSay%20-%20SaaS%20Terms%20and%20Conditions%20-%20clean.doc?dl=0

**Comment by Pavek** [comment]
Questions:
- How to show this content? Having that we have Single-Page design, I suppose this should be a simple Modal dialog. Correct?
- Where to link them from?

**Comment by assafharel** [comment]
The link is from the bottom of the page (the black part) underneath "how it works" and "contact".

Regrading Modality - no that's not what I had in mind. I prefer a white page just with the header and footer of the original landing page (that still works, header stays on top, links take you back to how it works and contact, etc.). Look at DaPulse.com, Trello.com, Basecamp.com, etc. for examples / inspiration...

**Comment by Pavek** [comment]
The sites you linked are *not* single-page websites, so for them a separate page is a natural choice.

As example of a single-page approach (modal), please see this page: http://www.iubenda.com/ (incidently they also generate given policies) -- click the links at the very bottom.

Separate pages are also fine, but probably more complex and less intuitive.

**Comment by assafharel** [comment]
I see. In that case, modal window like in  http://www.iubenda.com/ is also fine.
