### ISSUE TITLE
new landing page | "send message" should send to contact@peer-say.com

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#63]
(and not hello@peer-say.com)

**Comment by Pavek** [comment]
The behavior of the Contact Form is unspecified. So I have  the following questions/guesses:
- server should attempt to send an email to the address with a message inserted:
  - so the message field is required I guess. What about the other fields?
  - what should be the Title of the message? How to use provided name?

- how to respond on form submit:
  - show 'Thank you' message? How/where? (image is preferable)
  - allow sending second message too?

Also we have a Subscribe form in Footer. It is not clear how it works too or if this is needed at all at this stage.

**Comment by assafharel** [comment]
To: contact@peer-say.com
Relpy to: email
Subject: [Landing Page] Hello from <name>
<message>

Respond to submit: add text underneath the message box saying "sending message" that changes to "message sent" after 1 sec. Don't bother with errors, etc. in case it wasn't sent. Throw in a nice progress circle (for the 1 sec. while sending). I tried drawing it (attached), but I'm not a designer... for instance, use the same font and color and size as in the message (I didn't have it), align to the left, etc.

Regarding blocking 2nd message - I don't see how you can block it - I can always load the page again and send again, etc. If it's not too difficult, yes, allow only 3 e-mails, and then block the send button, or give an ambiguous error message like "too many messages" in red at the same place of the "message sent" status.

Regarding subscribe - I agree that it's redundant. Please remove.

![screen shot 2015-04-07 at 8 35 12 am](https://cloud.githubusercontent.com/assets/8779321/7017893/bbbba410-dd06-11e4-892b-bcc5daf7e615.png)
