### ISSUE TITLE
Applying an existing topic to a new requirement doesn't work

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#75]
I added a new requriement using 'Click to add'.
I tried to apply one of the topics I added previously.
The topic did not apply (requirement remained without topic).

**Comment by Pavek** [comment]
Failed to reproduce on current version in production. Please check that version too and add reproduction details.

**Comment by Pavek** [comment]
I realized what happens: to apply a topic (make a selection) user shoul select and item and click Enter - this is how this control works by default. Not sure if this can be changed.

Please check if this is OK and can be closed.
