### ISSUE TITLE
There is no way to edit a project name

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#78]
The essentials do not show the name and there is no way to edit it once created.

**Comment by Pavek** [comment]
Please suggest UI for it. If it's just a new field on Essentilas page, please specify:
- position
- label (if any)
- placeholder

Or just send new mock-up :)

**Comment by assafharel** [comment]
Just make the string editable. Same position as it is now.

**Comment by Pavek** [comment]
We have 2 types of inline edits now:
- editable tablle cell (Project Title is not in table, so cannot re-use, need to implement anew)
- Summry/Recommendation fields (a-la Trello, complete with cancel/save controls) and title was edited like this in the past.

Please elaborate.

**Comment by assafharel** [comment]
Can't the text, as it, be made editable?
I don't want to change the way it look & feel, just to be able to click in it, make it editable, change it, and pressing enter / clicking outside, to finish editing.

**Comment by Pavek** [comment]
This is possible, but here's the issues:
- there is no cancel (accidental removal)
- how to pevent saving empty name? is it needed? what to show instead if not? (both in Project Details & tile in Project List)
- editing mode requires some styles I guess (I will come up with something)

**Comment by assafharel** [comment]
One idea that came in the meeting with Udi Weinstein is to always call the project in the name of the category - so it's always mail security project or load balance project or IaaS project, etc., etc.
This suggests moving the category selector to the new project creator, and removing it from essentials. Generally, we get a lot of rejects from the essentials page, that makes us want to remove it altogether. So lets postpone this issue - and rename it to - make the name of the project the name of the category (+ the word project), and work on it in the 2nd sprint (when we add the presentation, and optionally remove essentials).

**Comment by assafharel** [comment]
duplicate for issue#122

**Comment by assafharel** [comment]
One more thing from a UX review:
The "Create New" button should always be clickable.
If the user didn't select a category yet, surround the field with a red triangle and a message, just as you did in the registration form of the landing page.

**Comment by Pavek** [comment]
Fixed by making Title == Category.
