### ISSUE TITLE
Missing feature - no way to classify criteria as must/optional

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#83]

**Comment by assafharel** [comment]
Tal, I'm assigning it back to you, as it requires design.
I also don't think that it's a show stopper, as we don't use the notion of must-have in the table calculations.

**Comment by assafharel** [comment]
Design: Add a field called "Mandatory" to the list of criteria with Check Boxes. User can check it and make a criteria mandatory. Add such a column as well in the decision table to the left of the weight.
If it's possible add a grade "not supported" to the grade cell, and if such a product doesn't support that mandatory criteria, make the entire grade column grey.

Assaf

**Comment by Pavek** [comment]
Th second part of the requirement -- 'If it's possible add a grade "not supported" to the grade cell' -- is tricky.

Grade cell holds <input type="number"> element. This adds several important properies by broswer: up/down spinner buttons (some browsers), validation (min/max), etc. But this measn that entering text is not allowed and thus it is unclear how to implement 'not supported' behavior of this control.

**Comment by assafharel** [comment]
I suggested it because it's very easy to put 0, and then the entire product becomes grey, and it's not very clear. Maybe if you start with the grade 10, for each field by default, then the problem will disappear. Or maybe add "-1" with tool-tip "unsupported". Or maybe start with empty cell, and when clicking up and down you start with 5, or 7, or 9. Something far away from 0.

**Comment by Pavek** [comment]
Thanks for different suggestions. So, I think making 10 a default grade is the most easy/non-cumbersome solution. Also I will experiment with tooltip/label shown when grade becomes 0 (meaning 'not supported').

**Comment by assafharel** [comment]
OK, good. Tal also requested that it will be visible (different gray color maybe?), which are the mandatory fields that are making this product grey.

**Comment by Pavek** [comment]
This is fixed with 2 commits above.
