### ISSUE TITLE
The 'Load More' behavior in the Criteria page is very confusing

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#84]
Clicking 'Load More' adds items under all topics.
The expected behavior is that more will be added in the end, and users will not notice that items were added all over.
A different approach is needed.

A quick option could be:
Show all criteria, but add a 'Collapse/Expand' for each topic and start with all topics collapsed.
(It is not the best solution, but current behavior is very unclear).

**Comment by Pavek** [comment]
This was fixed with:
a) Load all criteria (may be wrong decision long-term)
b) Add show less / show more logic
