### ISSUE TITLE
Essentials: Unit options for budget should be different

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#87]
We don't expect Million dollar projects, so no need for a 'Millions' unit.
The units are either as-is (e.g. Dollars) or Thousands (K).

The presentation as a letter at the end of the line is strange.
I suggest adding a dropdown between the currency selector and the value with either a '----' or 'Thousands' in it.
If Thousands is selected, then when showing the summarized view of essentials data the letter K can is added to the value.

**Comment by Pavek** [comment]
This was fixed by Assaf + formatting of budget fix (#91).
