### ISSUE TITLE
Criteria filter: Doesn't always work

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#92]
I changed to a 'Selected' filter - and saw unselected requirements.

**Comment by assafharel** [comment]
Can you try to reproduce the exact user scenario?
I never saw it, and I'm guessing that Pavel will have hard time reproducing as well...
It is a show stopper, though, just a needle in a hey stack to reproduce, if you don't provide us with exact steps to reproduce.

**Comment by Pavek** [comment]
Fixed by removing filters.
