### ISSUE TITLE
Decision table showed me criteria not appearing in the list of requirements

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#93]
I see 'Minimal False Positives' in the table - but can't find it in the full list.
I think I am not seeing the full list - the lowest popularity I see (under 'Technology') is 75% and I am guessing there are more.

**Comment by Pavek** [comment]
There are only 10 items loaded sorted by popularty. The rest is loaded by LoadMore btn, 10 at a time and btn is hidden when done.
