### ISSUE TITLE
RFE: Add a user description for a requirement

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#95]
Allow users to add their own description to a criteria, so add the specific meaning for their evaluation.

**Comment by assafharel** [comment]
Tal, please suggest a UI for this, as there's no place for it right now.
Assigning the issue back to you, as Pavel should not be the one deciding that.

**Comment by assafharel** [comment]
The suggestion: make the description field editable. Users will be able to edit and change / add to the original description.

**Comment by Pavek** [comment]
Just to clarify: do you mean editable in Requirements page table? Asking becasue I think user asked to add it to Decision table, and this solution doesn't affect Decision table as description is not displayed there.

**Comment by assafharel** [comment]
Yes, I mean in requirements page table.
Users read the requirement descriptions and wanted to change / add / clarify them to their best understanding.

Assaf

**Comment by Pavek** [comment]
Also remebered: editable description can be only for selected items. Unselected items reside in read-only global collection. Selected are the copies of global ones to Project doc and are indeed editable.

Note: it leads to some shaky consequences: e.g. unselecting item effectively removes customs description forever and then it is a dilemma: add special code to roll-back global description immediately or leave it and let user see it on next API call / page re-visit.

**Comment by assafharel** [comment]
After a user changes a description, she doesn't want to see the old one any more (regardless of the selection status). You may add a delete or rollback, etc. option that brings back the "old" description from the server.

**Comment by Pavek** [comment]
Here's alternative idea to edit description, which I think is more consistent with other UI and don't produce unwanted-side-effects:
- after user selects and item, it gets new controls (icons) added to it: Edit & Delete (edit will be also added to new custom items)
- then user can click Edit icon which opens Add New / Edit form and fields are populated with editable content. Clicking Save changes the Description/Name etc.
- when user unselects an item, it remain in the list and with the edit/delete icons and with modified content (i.e, remains private and stored in DB)
- when user deletes item, then it is removed from DB and a public item is displayed instead of it -- without edit/delete icons (this may be confusing actually).

Thoughts?

**Comment by assafharel** [comment]
I like it. Looks like the quickest and most easy fix.
Go ahead. We will test it with users, and re-open if it's not clear to the users.

**Comment by assafharel** [comment]
Re-openning.
When clicking edit on a criteria at the bottom of the page, you don't see that it changed the new fields at the top.
So the suggestion is to add an edit line below the line that is currently being edited. That line will be used only to edit that line above it, and you close it with a close button or x or something like that.

Assaf

**Comment by assafharel** [comment]
With the new accordion control, there's a slight tweak to the new requirement as well: It should be allow to add a new requirement for a topic, by clicking +New on the topic bar. This should open the +"New" control directly below the topic (with topic field already filled or not exist (as it's known)).

**Comment by Pavek** [comment]
This is somewhat in conflict with what I changed recently, namely:
 - added a triangle chevron to indicate a link between form and [(+) New]
button (it helps in scenario when form is opened by search, which wasn't
quite clear, IMO)
 - also the link is further strengthened by changing button style to
'active' while form is open and removing (-)/(+) icon switching (this of
course means that edit requirement cannot be used with this form anymore
and inline form will be used instead)

Note: setting a form's topic value to currently open Topic (if any) is fine
with me.



Pavel

**Comment by assafharel** [comment]
I'm not sure I understand the conflict with what I've wrote, 
but assuming you're going to open the "+New form" immediately under the line (with that line information already written) that is being edited, or the topic that is being a criteria is being added to, I agree.

Assaf

**Comment by assafharel** [comment]
Re-opening.
1 problem, and 1 missing implementation.

Problem: It shouldn't be allowed to edit the Name and the topic.
They can simply not exist in the control, or be read-only.

Missing: The option to add new to a topic.
This is highly required, with the new accordion UI, as the user is adding requirements topic by topic, so the notion of a missing requirement is usually in the context of a topic. 

Assaf

**Comment by Pavek** [comment]
1. 'edit the Name and the topic.'
OK, but my opinion this is bad design.

2. Missing: The option to add new to a topic.
 (I guess this is about adding new Requirement to currently open Topic)
This is implemented according to what we discussed - currently open Topic
(if any) sets the default Topic for newly added Requirements, that is:
 - if currently open Topics is X, and
 a) user clicks New button => addNew form is opened with topic X selected
by default (can be changed of course)
 b) user uses search and hits Enter when no items found => addNew form is
opened with topic X *and* Name as entered in search

- if not Topics are open (all accordion items are closed), then the same as
above except that default topic is empty


Pavel

**Comment by assafharel** [comment]
1. 'edit the Name and the topic.'
OK, but my opinion this is bad design.

We will test it with users, and see their behavior. You're assuming that read-only will be annoying, and we think that anything else confuses the users, so we'll just wait and see their reaction.

2. Missing: The option to add new to a topic.
 (I guess this is about adding new Requirement to currently open Topic)
This is implemented according to what we discussed - currently open Topic
(if any) sets the default Topic for newly added Requirements, that is:
 - if currently open Topics is X, and
 a) user clicks New button => addNew form is opened with topic X selected
by default (can be changed of course)

What I'm missing is a "Add New" control in the topic ribbon that opens the form under the topic. The user is unaware of the "Add New" button at the top of the page, when working on a specific topic. 

 b) user uses search and hits Enter when no items found => addNew form is
opened with topic X *and* Name as entered in search

- if not Topics are open (all accordion items are closed), then the same as
above except that default topic is empty


Pavel

**Comment by assafharel** [comment]
What I'm missing is an "Add New" control in the topic ribbon that opens the form under the topic.
The user is unaware of the "Add New" button at the top of the page, when working on a specific topic. 

BTW, a 2nd click on the edit button should close the form (just like a 2nd click on the "+New” button close the form on top.

Thanks,
Assaf


Assaf Harel, CTO and Co-Founder,
+972.52.7206732

**Comment by Pavek** [comment]
Just to clarify the requirements + questions:
 - remove (+) New button from top of the page
  -  Q: Products page too?

 - create N buttons instead, one per Header of every topic.
  Q: what is the location of these buttons?

 - clicking the button opens a form inside uncollapsed accordion section,
just above the table
 - click also uncollapses(reveals) the section if it is collapsed.

  Q: what about the scenario with search + add new? Which accordion section
should be open & form displayed?


>> BTW, a 2nd click on the edit button should close the form (just like a
2nd click on the "+New” button close the form on top.
OK

Pavel

**Comment by assafharel** [comment]
Don't remove it from the top and don't remove it from products. Just add a new one per topic. The top New still responds to search.

**Comment by Pavek** [comment]
OK - got it.

Having no location hints, should I assume this?
http://gyazo.com/2976a14ebc86663615275d6990617e74


Pavel

**Comment by assafharel** [comment]
Better put it to the right.

Assaf
בתאריך Wed, Jul 15, 2015 ב-18:13 מאת Pavel Zhytko <notifications@github.com

**Comment by assafharel** [comment]
One more thing: have the +New visible only when the topic is open.
