### ISSUE TITLE
Decision table weights should not start with 1

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#97]
Instead use this algorithm: Divide 100 to the selected topics, (for instance if 4 topics, each topic gets 25), now divide each topic to its sub criteria, such that 3 criteria get (25/3 = 8 1/3) 8 and 9 and 6 criteria get 4 and 5.

**Comment by Pavek** [comment]
Let's please define the algorythm in the following terms:
scenario a):
1. User added 1st criteria (assuming enough products added too), it's weight is X
2. User added 2nd criteria, it's weight is Y (note: it is preferable that X is not changed, otherwise it leads to cascade updates which is not good)
3. etc.

scenario b):
1. User added Nth criteria, it's weight is Z
2. User updates this criteria weight to Z'
3. User add's N+1 criteria, it's weight becomes: W (accounting for manual weight chages)

**Comment by assafharel** [comment]
Lowered the priority to Medium, as it's less important then the rest of the issues for Sprint#1.
If EOW deasdline cannot be met, this is the first issue to postpone to Sprint#2, Sprint#3 or even to Someday...

**Comment by assafharel** [comment]
Per UX review, and some user research:

1. The 100% is divided between topics. Price is usually 40%-50%, Technology is 20%, Vendor is 30%, etc. So - start with dividing the 100% evenly between selected topics. When a topic is added, recalculate this, so the weights are evenly divided (even if the user changed it before adding a new topic).
Notice that these are [0%-100%] fields, and it adds up to 100%.
Please add spinners to the sub titles (topics), and allow to user to +/-5% (or manually edit to any integer in the range [0%-100%].
Total should be 100%. If it's not mark it with a Red rectangle and a tool tip that says - "Total should be 100%", when mouse hovers.

2. Inside each topic the weights are evenly divided and are from the range [0-5]. When the user clicks up and down on the spinner, the user sees a tool tip that shows the percentile from the entire 100%, but the division is within the topic.
Example - Let's assume we talk about the topic "cost" and that the user marked it as 40%. Within it there are 2 selected criteria "Price" and "Cost Structure" that starts with 1, so both get 20% tool tip. Now you increment Price to 3, so Price is now 30% and Cost structure is 10%.
Adding a new criteria under cost, immediately sets it back to evenly distributed, and the user will have to re-work the balance between the criteria. Still, it will be just from the 40% of the cost topic, with no impact on the rest of the topics.

**Comment by Pavek** [comment]
Implemented according to last conversation.
