### ISSUE TITLE
Decision table should be wider then the rest of the panes. You can asssume a wider screen, and not so good experience for narrower experience (==mobile).

### ISSUE THREAD

**Issue by assafharel** [PeerSay/Atlas#99]

**Comment by assafharel** [comment]
The new solution for proto#3, sprint#1 is to fix the column sizes and add a horizontal scroll, so we can support endless products.

**Comment by assafharel** [comment]
I'm reopening because the User Experience of the wide screen toggle is not good enough.
It doesn't keep state (i.e. you go back and forth and it's closed), there are panes that it exists and panes that it doesn't.
Please change it, such that it appears on all the windows, and that it's always on the same positions on all windows.

Thanks,
Assaf

**Comment by Pavek** [comment]
1. OK for persitence & global state
2. yes, I omitted it for some pages, becasue it looked a bit odd to me. Please conform that e.g. Essentails page like this is OK:
http://gyazo.com/12caee83df46c8683bf6b672b8a31e50

**Comment by assafharel** [comment]
Confirmed
בתאריך Tue, Jul 7, 2015 ב-18:14 מאת Pavel Zhytko <notifications@github.com>:
